### ISSUE TITLE
Request for bumping uno-sdk and imgui versions

### ISSUE THREAD

**Issue by HamiltonHuaji** [kotlin-graphics/mary#572]
There is a significant change (3000+ commits) between the newest imgui version (1.89.7) and the current version (1.79) in this repository. Therefore, it would be beneficial to upgrade them.

**Comment by elect86** [comment]
1.89.7 is present

**Comment by HamiltonHuaji** [comment]
Oh, my mistake. However, when I checked the kotlin/graphics/imgui-vk directory, I noticed that it seems that only version 1.79 is available. Is this the expected behavior? (I think I must have confused imgui-vk with imgui when writing this issue. Sorry for the inconvenience)
Edit: As for the part mentioned about "uno" in this issue, I now realize it is because there seems to be two duplicate "uno" directories, one of which only has version 0.7.11.

**Comment by elect86** [comment]
So, let me explain that, the "problem" is that I need to finish to implement auto-generation for vkk, which will be used in imgui-vk, but last time I was working on that I was blocked by some bugs in the official Vulkan docs api

I'll resume work on that sooner or later

**Comment by elect86** [comment]
But for the moment, imgui-vk is simply disabled 

It can still be used in projects using Vulkan, though
